// Load translations
let translations = {
  "es": {
    "index": {
      "quien-soy": "¿Quién soy?",
      "habilidades": "Habilidades",
      "proyectos": "Proyectos",
      "contacto": "Contacto"
    },
    "quien-soy": {
      "nav-quien-soy": "Quién soy",
      "nav-habilidades": "Habilidades",
      "nav-proyectos": "Proyectos",
      "nav-contacto": "Contacto",
      "mensaje-1": "LA MEJOR MANERA",
      "mensaje-2": "DE PREDECIR",
      "mensaje-3": "EL FUTURO",
      "mensaje-4": "ES CREÁNDOLO",
      "bio1-h3": "¡Hola!",
      "bio1-p1": "Mi nombre es César Delgado. Soy diseñador gráfico, psicólogo y actualmente me estoy formando como desarrollador web frontend. Muy loco, ¿verdad? Pero créeme, <strong>todo tiene mucho sentido.</strong>",
      "bio1-p2": "Como diseñador gráfico, he podido trabajar en diversas agencias, litografías y empresas en los casi 15 años que tengo de experiencia. Aunque pude desenvolverme en muchos roles, <strong>mi fuerte siempre estuvo en la parte de identidad corporativa, más específicamente en la creación de logos, así como diseñar piezas gráficas para fines de tanto de impresión como de uso digital.</strong> También tuve la gran oportunidad de ejercer la docencia, siendo incluso el coordinador del programa de Diseño Gráfico y director creativo en el instituto donde laboré.",
      "bio1-p3": "Como psicólogo, ya son 8 años de experiencia. Sin embargo, aunque como todo psicólogo ejercí la parte clínica, <strong>mi enfoque estuvo mucho más dirigido hacia cómo funcionaba el comportamiento del consumidor, para así generar un mayor impacto visual en los clientes potenciales.</strong> También fui docente de psicología y funcioné como coordinador de Bienestar Institucional.",
      "bio1-p4": "Intentando darle un aire a mi formación como creativo, opté por aprender a desarrollar páginas web, lo cuál me ha resultado fascinante. Primero empecé con formación empírica a finales de 2023, y luego decidí estudiar en un Bootcamp para ampliar mis conocimientos. <strong>A pesar de que no cuento con mucha experiencia, es solo cuestión de tiempo para convertirme en uno de los mejores desarrolladores web Frontend.</strong>",
      "ts-titulo-h3": "¿QUÉ ME",
      "ts-titulo-h2": "CARACTERIZA",
      "bio2-acordeon-1": "Lo que hago",
      "bio2-p1": "Me dedico a brindar asesoramientos sobre identidad corporativa, para que mis clientes tengan un posicionamiento de marca inicial, de acuerdo a los estándares gráficos del mercado y lograr un impacto positivo en sus clientes fijos y potenciales.",
      "bio2-acordeon-2": "Lo que soy",
      "bio2-p2": "Soy una persona que le encanta compartir su conocimiento con otros, brindando soluciones gráficas de cualquier tipo. Asimismo, me encanta aprender cada día algo nuevo, todo con tal de mejorar de manera integral.",
      "bio2-acordeon-3": "Lo que quiero llegar a ser",
      "bio2-p3": "Quiero ser un referente tanto del diseño gráfico como del diseño web, integrando mis conocimientos en ambas áreas y alcanzando mercados internacionales por mi calidad, eficiencia y profesionalismo.",
      "servicios-title": "MIS SERVICIOS",
      "servicio1-h3": "CREACIÓN DE LOGOS",
      "servicio1-p": "He tenido la gran fortuna de darle una cara a los negocios de nuevos emprendedores, así como renovar la imagen de muchas empresas consolidadas en el mercado. Procuro seguir los estándares del mercado, tratando que los logos que diseño tengan no solo impacto visual, sino también que cumplan con los requerimientos mínimos de creación de marca y perdurabilidad en el tiempo.",
      "servicio2-h3": "DISEÑO DE PIEZAS GRÁFICAS",
      "servicio2-p": "Con más de 14 años de experiencia, he trabajado en diversas agencias y litografías, ampliando mi repertorio de conocimientos sobre piezas gráficas digitales e impresas. Mi mayor énfasis está en generar diseños frescos que sepan representar el ADN de mis clientes, así como también plasmar la intención comunicacional de lo que se quiere transmitir.",
      "servicio3-h3": "DESARROLLO WEB FRONTEND",
      "servicio3-p": "Esta es mi incursión más nueva y a la que le estoy poniendo todo mi empeño. Implemento toda mi experiencia en diseño gráfico para crear entornos web agradables e impactantes visualmente. Constantemente estoy puliendo mi técnica para saber cuáles son las últimas tendencias de desarrollo de páginas web, para así ampliar mi catálogo de servicios web. Mi mayor aspiración es adquirir la competencia de Desarrollador Web Fullstack. Mientras tanto, me preparo para ser el mejor Front.",
      "explora-titulo-h2": "¿TE GUSTA LO QUE VES?",
      "explora-habilidades-h3": "¡Échale un ojo a esto!",
      "explora-habilidades-p": "¿Te gustaría ver un detallado mejor sobre mis competencias, habilidades y aptitudes? ¿O más bien deseas ver una muestra de mi trabajo como diseñador gráfico y desarrollador web? Entonces no dudes en revisar estas secciones para que puedas convencerte de mi trabajo. :D",
      "explora-botones-h3-1": "Ir a Habilidades",
      "explora-botones-h3-2": "Ir a Proyectos",
      "footer-info-left": "CeDev © 2024 | Todos los derechos reservados.",
      "footer-menu-quien-soy": "Quién soy",
      "footer-menu-habilidades": "Habilidades",
      "footer-menu-proyectos": "Proyectos",
      "footer-menu-contacto": "Contacto"
    },
    "habilidades": {
      "nav-quien-soy": "Quién soy",
      "nav-habilidades": "Habilidades",
      "nav-proyectos": "Proyectos",
      "nav-contacto": "Contacto",
      "typewriter": "NUNCA ES TARDE PARA EMPEZAR. LO QUE IMPORTA ES QUE COMIENCES.",
      "fa-titulo-h3": "Formación académica",
      "inst-texto-h4-1": "Fundación Academia de Dibujo Profesional",
      "inst-texto-p1-1": "Técnico Profesional en Diseño Gráfico",
      "inst-texto-p2-1": "2010 | Cali, Colombia.",
      "inst-texto-h4-2": "Universidad Antonio Nariño - Sede Buga",
      "inst-texto-p1-2": "Profesional en Psicología",
      "inst-texto-p2-2": "2017 | Buga, Colombia.",
      "inst-texto-h4-3": "Platzi SAS",
      "inst-texto-p1-3": "Desarrollo Web",
      "inst-texto-p2-3": "2022 | On-line.",
      "inst-texto-h4-4": "Bogotá Institute of Technology - BIT",
      "inst-texto-p1-4": "Bootcamp Desarrollo Web Fullstack",
      "inst-texto-p2-4": "2024 | On-line.",
      "skills-container-h2": "Mis Habilidades",
      "skill-label-corel": "Corel Draw: 100%",
      "skill-label-illustrator": "Illustrator: 80%",
      "skill-label-photoshop": "Photoshop: 70%",
      "skill-label-filmora": "Filmora: 80%",
      "skill-label-vsc": "VSC: 70%",
      "tech-container-h2": "Tecnologías",
      "circle-name-html": "HTML - 90%",
      "circle-name-css": "CSS - 80%",
      "circle-name-js": "JavaScript - 60%",
      "circle-name-mongodb": "MongoDB - 50%",
      "circle-name-angular": "Angular - 50%",
      "circle-name-nodejs": "Node JS - 50%",
      "circle-name-figma": "Figma - 80%",
      "spec-title-h2": "Mis especialidades",
      "spec-text-p1": "Diseño de logos",
      "spec-text-p2": "Diseño litográfico",
      "spec-text-p3": "Diseño digital",
      "spec-text-p4": "Maquetación web",
      "languages-h2": "Idiomas",
      "language-p1": "Inglés - C1",
      "language-p2": "Francés - A1",
      "footer-info-left": "CeDev © 2024 | Todos los derechos reservados.",
      "footer-menu-quien-soy": "Quién soy",
      "footer-menu-habilidades": "Habilidades",
      "footer-menu-proyectos": "Proyectos",
      "footer-menu-contacto": "Contacto"
    },
    "proyectos": {
      "nav-quien-soy": "Quién soy",
      "nav-habilidades": "Habilidades",
      "nav-proyectos": "Proyectos",
      "nav-contacto": "Contacto",
      "mensaje-proyectos-h2": "DÉMOSLE IDENTIDAD",
      "mensaje-proyectos-h1": "A TU MARCA",
      "presentacion-texto-h3": "¡Mira mis muestras de trabajo!",
      "presentacion-texto-p1": "Les presento una pequeña muestra de todas piezas gráficas y páginas web que he podido hacer, tanto en estos 14 años como diseñador gráfico, así como en este corto tiempo que me he dedicado a aprender de desarrollo web. Espero que sean de tu agrado y veas que <strong>tu marca o idea, puede estar en las mejores manos.</strong>",
      "presentacion-texto-p2": "¡Que lo disfrutes!",
      "proyectos-logos-h3": "Logos",
      "proyectos-volantes-h3": "Volantes",
      "proyectos-editorial-h3": "Diseño editorial",
      "proyectos-web-h3": "Proyectos web",
      "lightbox-logo-1-h3": "Logo Awesome! Escuela de idiomas",
      "lightbox-logo-2-h3": "Unidad de Desarrollo Vocacional - UDEV",
      "lightbox-logo-3-h3": "Fantasy Star",
      "lightbox-logo-4-h3": "Laboratorio Experimental de Publicidad - LEP",
      "lightbox-logo-5-h3": "Pancci Panificadora",
      "lightbox-logo-6-h3": "ITA Nexus Lab",
      "lightbox-logo-7-h3": "Lorena Barbosa - Psicóloga",
      "lightbox-logo-8-h3": "Grupo Aptos SAS",
      "lightbox-logo-9-h3": "Di' Milán - Productos Artesanales",
      "lightbox-logo-10-h3": "Consentir - Grupo Pedagógico",
      "lightbox-volante-1-h3": "Volante ITA Profesional - Programa de Gastronomía",
      "lightbox-volante-2-h3": "Volante Licores La 4ta Avenida",
      "lightbox-volante-3-h3": "Volante Crackling - Súper Panceta Express",
      "lightbox-volante-4-h3": "Volante Somos Cultura, Somos de la Gente - Lanzamiento",
      "lightbox-volante-5-h3": "Volante Awesome! Escuela de Idiomas",
      "lightbox-volante-6-h3": "Volante lanzamiento single Me Llamas",
      "lightbox-volante-7-h3": "Volante promocional cursos UDEV",
      "lightbox-volante-8-h3": "Volante para redes - Clínica Denta",
      "lightbox-editorial-1-h3": "Revista Cibeles Pharma",
      "lightbox-editorial-1-p": "Haz click aquí para ver la revista",
      "lightbox-editorial-1-p2": "(Se abrirá en una nueva pestaña)",
      "lightbox-editorial-2-h3": "Catálogo de productos - Avequipos",
      "lightbox-editorial-2-p": "Haz click aquí para ver la revista",
      "lightbox-editorial-2-p2": "(Se abrirá en una nueva pestaña)",
      "lightbox-editorial-3-h3": "Portafolio de servicios - I.E. San Giuseppe Moscati",
      "lightbox-editorial-3-p": "Haz click aquí para ver la revista",
      "lightbox-editorial-3-p2": "(Se abrirá en una nueva pestaña)",
      "lightbox-editorial-4-h3": "Portafolio de servicios - Clínica Denta",
      "lightbox-editorial-4-p": "Haz click aquí para ver la revista",
      "lightbox-editorial-4-p2": "(Se abrirá en una nueva pestaña)",
      "lightbox-editorial-5-h3": "Cartilla para diplomado - ITA Profesional | CVC | Patryo",
      "lightbox-editorial-5-p": "Haz click aquí para ver la revista",
      "lightbox-editorial-5-p2": "(Se abrirá en una nueva pestaña)",
      "lightbox-editorial-6-h3": "Revista informativa - I.E. República de Israel",
      "lightbox-editorial-6-p": "Haz click aquí para ver la revista",
      "lightbox-editorial-6-p2": "(Se abrirá en una nueva pestaña)",
      "lightbox-web-1-h3": "Tienda Virtual Nintendo BenShop",
      "lightbox-web-1-p": "Sitio web creado con HTML, CSS y JS, usando localStorage para el carrito de compras.",
      "lightbox-web-1-p2": "Haz click aquí para ver la página",
      "lightbox-web-1-p3": "(Se abrirá en una nueva pestaña)",
      "lightbox-web-2-h3": "La Agencia",
      "lightbox-web-2-p": "Mock up de página web para agencia creativa.",
      "lightbox-web-2-p2": "Haz click aquí para ver la página",
      "lightbox-web-2-p3": "(Se abrirá en una nueva pestaña)",
      "lightbox-web-3-h3": "PokéAPI",
      "lightbox-web-3-p": "Proyecto web usando la API de PokéAPI.com, pudiéndose filtrar los Pokémon por tipos.",
      "lightbox-web-3-p2": "Haz click aquí para ver la página",
      "lightbox-web-3-p3": "(Se abrirá en una nueva pestaña)",
      "lightbox-web-4-h3": "Página de conteo regresivo",
      "lightbox-web-4-p": "Sencillo proyecto web de conteo regresivo, pudiéndose adaptar a distintos propósitos.",
      "lightbox-web-4-p2": "Haz click aquí para ver la página",
      "lightbox-web-4-p3": "(Se abrirá en una nueva pestaña)",
      "lightbox-web-5-h3": "Varelas Bistró",
      "lightbox-web-5-p": "Proyecto web de e-commerce con registro y login funcionales, integrando un backend hecho con MongoDB y montado en servidor Digital Ocean con dominio real.",
      "lightbox-web-5-p2": "Haz click aquí para ver la página",
      "lightbox-web-5-p3": "(Se abrirá en una nueva pestaña)",
      "footer-info-left": "CeDev © 2024 | Todos los derechos reservados.",
      "footer-menu-quien-soy": "Quién soy",
      "footer-menu-habilidades": "Habilidades",
      "footer-menu-proyectos": "Proyectos",
      "footer-menu-contacto": "Contacto"
    },
    "contacto": {
      "nav-quien-soy": "Quién soy",
      "nav-habilidades": "Habilidades",
      "nav-proyectos": "Proyectos",
      "nav-contacto": "Contacto",
      "cont-texto-h2": "ESTÁS A UN PASO DE PERPETUAR LA IMAGEN DE TU NEGOCIO",
      "cont-texto-p": "¿Listo para que trabajemos juntos? Tu emprendimiento dirá algo más que un simple \"¡Hola, mundo!\". Hagamos que tenga una verdadera huella en el mundo digital e impreso.",
      "contacto-formulario-h4": "¿Quieres enviarme un mensaje?",
      "form-nombre-placeholder": "Nombre",
      "form-email-placeholder": "Email",
      "form-tema-placeholder": "¿De qué quieres hablarme?",
      "form-tema-option-1": "Cotización de logo",
      "form-tema-option-2": "Paquete de diseños",
      "form-tema-option-3": "Otros",
      "form-mensaje-placeholder": "Escribe algo...",
      "form-boton": "Enviar",
      "footer-info-left": "CeDev © 2024 | Todos los derechos reservados.",
      "footer-menu-quien-soy": "Quién soy",
      "footer-menu-habilidades": "Habilidades",
      "footer-menu-proyectos": "Proyectos",
      "footer-menu-contacto": "Contacto"
    }
  },
  "en": {
    "index": {
      "quien-soy": "Who am I?",
      "habilidades": "Skills",
      "proyectos": "Projects",
      "contacto": "Contact"
    },
    "quien-soy": {
      "nav-quien-soy": "Who am I?",
      "nav-habilidades": "Skills",
      "nav-proyectos": "Projects",
      "nav-contacto": "Contact",
      "mensaje-1": "THE BEST WAY",
      "mensaje-2": "TO PREDICT",
      "mensaje-3": "THE FUTURE",
      "mensaje-4": "IS TO CREATE IT",
      "bio1-h3": "Hello!",
      "bio1-p1": "My name is César Delgado. I am a graphic designer, psychologist, and currently training to become a frontend web developer. Pretty crazy, right? But trust me, <strong>it all makes sense.</strong>",
      "bio1-p2": "As a graphic designer, I’ve had the opportunity to work in various agencies, print shops, and companies over nearly 15 years of experience. While I’ve taken on many roles, <strong>my strength has always been in corporate identity, particularly in creating logos, as well as designing graphics for both print and digital use.</strong> I also had the great opportunity to teach, even serving as the coordinator of the Graphic Design program and creative director at the institute where I worked.",
      "bio1-p3": "As a psychologist, I have 8 years of experience. However, while I practiced clinical psychology like any psychologist, <strong>my focus was much more on understanding consumer behavior to create a greater visual impact on potential clients.</strong> I also taught psychology and served as the coordinator of Institutional Welfare.",
      "bio1-p4": "Seeking to refresh my creative training, I decided to learn web development, which I’ve found fascinating. I started with self-taught training in late 2023 and later enrolled in a Bootcamp to expand my knowledge. <strong>Although I don’t have much experience yet, it’s only a matter of time before I become one of the best frontend web developers.</strong>",
      "ts-titulo-h3": "WHAT",
      "ts-titulo-h2": "DEFINES ME",
      "bio2-acordeon-1": "What I do",
      "bio2-p1": "I specialize in providing corporate identity consulting to help my clients establish an initial brand positioning that meets market graphic standards and creates a positive impact on their existing and potential customers.",
      "bio2-acordeon-2": "Who I am",
      "bio2-p2": "I’m someone who loves sharing knowledge with others, offering graphic solutions of all kinds. Likewise, I’m passionate about learning something new every day to improve holistically.",
      "bio2-acordeon-3": "What I aspire to be",
      "bio2-p3": "I aim to become a reference in both graphic design and web design, integrating my expertise in both fields and reaching international markets through my quality, efficiency, and professionalism.",
      "servicios-title": "MY SERVICES",
      "servicio1-h3": "LOGO CREATION",
      "servicio1-p": "I’ve had the great fortune of giving a face to the businesses of new entrepreneurs and refreshing the image of many established companies in the market. I strive to follow market standards, ensuring that the logos I design not only have visual impact but also meet the minimum requirements for brand creation and longevity.",
      "servicio2-h3": "GRAPHIC DESIGN",
      "servicio2-p": "With over 14 years of experience, I’ve worked in various agencies and print shops, expanding my knowledge of digital and printed graphic pieces. My main focus is on creating fresh designs that represent my clients’ DNA while effectively conveying the intended communication.",
      "servicio3-h3": "FRONTEND WEB DEVELOPMENT",
      "servicio3-p": "This is my newest venture, and I’m putting all my effort into it. I leverage my graphic design experience to create visually appealing and impactful web environments. I’m constantly refining my skills to stay updated with the latest web development trends, expanding my web services portfolio. My ultimate goal is to become a Fullstack Web Developer. For now, I’m working to be the best Frontend developer.",
      "explora-titulo-h2": "LIKE WHAT YOU SEE?",
      "explora-habilidades-h3": "Check this out!",
      "explora-habilidades-p": "Would you like to see a detailed overview of my competencies, skills, and abilities? Or perhaps you’d prefer to see a sample of my work as a graphic designer and web developer? Don’t hesitate to explore these sections to convince yourself of my work. :D",
      "explora-botones-h3-1": "Go to Skills",
      "explora-botones-h3-2": "Go to Projects",
      "footer-info-left": "CeDev © 2024 | Todos los derechos reservados.",
      "footer-menu-quien-soy": "Quién soy",
      "footer-menu-habilidades": "Habilidades",
      "footer-menu-proyectos": "Proyectos",
      "footer-menu-contacto": "Contacto"
    },
    "habilidades": {
      "nav-quien-soy": "Who am I?",
      "nav-habilidades": "Skills",
      "nav-proyectos": "Projects",
      "nav-contacto": "Contact",
      "typewriter": "IT’S NEVER TOO LATE TO START. WHAT MATTERS IS THAT YOU BEGIN.",
      "fa-titulo-h3": "Academic Background",
      "inst-texto-h4-1": "Fundación Academia de Dibujo Profesional",
      "inst-texto-p1-1": "Professional Technician in Graphic Design",
      "inst-texto-p2-1": "2010 | Cali, Colombia.",
      "inst-texto-h4-2": "Universidad Antonio Nariño - Buga Campus",
      "inst-texto-p1-2": "Professional in Psychology",
      "inst-texto-p2-2": "2017 | Buga, Colombia.",
      "inst-texto-h4-3": "Platzi SAS",
      "inst-texto-p1-3": "Web Development",
      "inst-texto-p2-3": "2022 | Online.",
      "inst-texto-h4-4": "Bogotá Institute of Technology - BIT",
      "inst-texto-p1-4": "Fullstack Web Development Bootcamp",
      "inst-texto-p2-4": "2024 | Online.",
      "skills-container-h2": "My Skills",
      "skill-label-corel": "Corel Draw: 100%",
      "skill-label-illustrator": "Illustrator: 80%",
      "skill-label-photoshop": "Photoshop: 70%",
      "skill-label-filmora": "Filmora: 80%",
      "skill-label-vsc": "VSC: 70%",
      "tech-container-h2": "Technologies",
      "circle-name-html": "HTML - 90%",
      "circle-name-css": "CSS - 80%",
      "circle-name-js": "JavaScript - 60%",
      "circle-name-mongodb": "MongoDB - 50%",
      "circle-name-angular": "Angular - 50%",
      "circle-name-nodejs": "Node JS - 50%",
      "circle-name-figma": "Figma - 80%",
      "spec-title-h2": "My Specialties",
      "spec-text-p1": "Logo Design",
      "spec-text-p2": "Print Design",
      "spec-text-p3": "Digital Design",
      "spec-text-p4": "Web Layout",
      "languages-h2": "Languages",
      "language-p1": "English - C1",
      "language-p2": "French - A1",
      "footer-info-left": "CeDev © 2024 | Todos los derechos reservados.",
      "footer-menu-quien-soy": "Who am I?",
      "footer-menu-habilidades": "Skills",
      "footer-menu-proyectos": "Projects",
      "footer-menu-contacto": "Contact"
    },
    "proyectos": {
      "nav-quien-soy": "Who am I?",
      "nav-habilidades": "Skills",
      "nav-proyectos": "Projects",
      "nav-contacto": "Contact",
      "mensaje-proyectos-h2": "LET’S GIVE IDENTITY",
      "mensaje-proyectos-h1": "TO YOUR BRAND",
      "presentacion-texto-h3": "Check out my work samples!",
      "presentacion-texto-p1": "Here’s a small sample of the graphic pieces and websites I’ve created over my 14 years as a graphic designer, as well as in the short time I’ve been learning web development. I hope you like them and see that <strong>your brand or idea is in the best hands.</strong>",
      "presentacion-texto-p2": "Enjoy!",
      "proyectos-logos-h3": "Logos",
      "proyectos-volantes-h3": "Flyers",
      "proyectos-editorial-h3": "Editorial Design",
      "proyectos-web-h3": "Web Projects",
      "lightbox-logo-1-h3": "Awesome! Language School Logo",
      "lightbox-logo-2-h3": "Vocational Development Unit - UDEV",
      "lightbox-logo-3-h3": "Fantasy Star",
      "lightbox-logo-4-h3": "Experimental Advertising Laboratory - LEP",
      "lightbox-logo-5-h3": "Pancci Bakery",
      "lightbox-logo-6-h3": "ITA Nexus Lab",
      "lightbox-logo-7-h3": "Lorena Barbosa - Psychologist",
      "lightbox-logo-8-h3": "Aptos Group SAS",
      "lightbox-logo-9-h3": "Di’ Milán - Handcrafted Products",
      "lightbox-logo-10-h3": "Consentir - Pedagogical Group",
      "lightbox-volante-1-h3": "ITA Profesional Flyer - Gastronomy Program",
      "lightbox-volante-2-h3": "La 4ta Avenida Liquors Flyer",
      "lightbox-volante-3-h3": "Crackling Flyer - Super Panceta Express",
      "lightbox-volante-4-h3": "We Are Culture, We Are People Flyer - Launch",
      "lightbox-volante-5-h3": "Awesome! Language School Flyer",
      "lightbox-volante-6-h3": "Me Llamas Single Launch Flyer",
      "lightbox-volante-7-h3": "UDEV Courses Promotional Flyer",
      "lightbox-volante-8-h3": "Social Media Flyer - Denta Clinic",
      "lightbox-editorial-1-h3": "Cibeles Pharma Magazine",
      "lightbox-editorial-1-p": "Click here to view the magazine",
      "lightbox-editorial-1-p2": "(Opens in a new tab)",
      "lightbox-editorial-2-h3": "Avequipos Product Catalog",
      "lightbox-editorial-2-p": "Click here to view the magazine",
      "lightbox-editorial-2-p2": "(Opens in a new tab)",
      "lightbox-editorial-3-h3": "Service Portfolio - I.E. San Giuseppe Moscati",
      "lightbox-editorial-3-p": "Click here to view the magazine",
      "lightbox-editorial-3-p2": "(Opens in a new tab)",
      "lightbox-editorial-4-h3": "Service Portfolio - Denta Clinic",
      "lightbox-editorial-4-p": "Click here to view the magazine",
      "lightbox-editorial-4-p2": "(Opens in a new tab)",
      "lightbox-editorial-5-h3": "Diploma Handbook - ITA Profesional | CVC | Patryo",
      "lightbox-editorial-5-p": "Click here to view the magazine",
      "lightbox-editorial-5-p2": "(Opens in a new tab)",
      "lightbox-editorial-6-h3": "Informative Magazine - I.E. República de Israel",
      "lightbox-editorial-6-p": "Click here to view the magazine",
      "lightbox-editorial-6-p2": "(Opens in a new tab)",
      "lightbox-web-1-h3": "Nintendo BenShop Virtual Store",
      "lightbox-web-1-p": "Website created with HTML, CSS, and JS, using localStorage for the shopping cart.",
      "lightbox-web-1-p2": "Click here to view the page",
      "lightbox-web-1-p3": "(Opens in a new tab)",
      "lightbox-web-2-h3": "La Agencia",
      "lightbox-web-2-p": "Mockup of a website for a creative agency.",
      "lightbox-web-2-p2": "Click here to view the page",
      "lightbox-web-2-p3": "(Opens in a new tab)",
      "lightbox-web-3-h3": "PokéAPI",
      "lightbox-web-3-p": "Web project using the PokéAPI.com API, allowing filtering of Pokémon by type.",
      "lightbox-web-3-p2": "Click here to view the page",
      "lightbox-web-3-p3": "(Opens in a new tab)",
      "lightbox-web-4-h3": "Countdown Page",
      "lightbox-web-4-p": "Simple web countdown project, adaptable to various purposes.",
      "lightbox-web-4-p2": "Click here to view the page",
      "lightbox-web-4-p3": "(Opens in a new tab)",
      "lightbox-web-5-h3": "Varelas Bistró",
      "lightbox-web-5-p": "E-commerce web project with functional registration and login, integrating a MongoDB backend and hosted on a Digital Ocean server with a real domain.",
      "lightbox-web-5-p2": "Click here to view the page",
      "lightbox-web-5-p3": "(Opens in a new tab)",
      "footer-info-left": "CeDev © 2024 | Todos los derechos reservados.",
      "footer-menu-quien-soy": "Who am I?",
      "footer-menu-habilidades": "Skills",
      "footer-menu-proyectos": "Projects",
      "footer-menu-contacto": "Contact"
    },
    "contacto": {
      "nav-quien-soy": "Who am I?",
      "nav-habilidades": "Skills",
      "nav-proyectos": "Projects",
      "nav-contacto": "Contact",
      "cont-texto-h2": "YOU’RE ONE STEP AWAY FROM ESTABLISHING YOUR BUSINESS’S IMAGE",
      "cont-texto-p": "Ready to work together? Your venture will say more than just a simple “Hello, world!” Let’s make it leave a real mark in the digital and print world.",
      "contacto-formulario-h4": "Want to send me a message?",
      "form-nombre-placeholder": "Name",
      "form-email-placeholder": "Email",
      "form-tema-placeholder": "What would you like to talk about?",
      "form-tema-option-1": "Logo quote",
      "form-tema-option-2": "Design package",
      "form-tema-option-3": "Other",
      "form-mensaje-placeholder": "Write something...",
      "form-boton": "Send",
      "footer-info-left": "CeDev © 2024 | Todos los derechos reservados.",
      "footer-menu-quien-soy": "Who am I?",
      "footer-menu-habilidades": "Skills",
      "footer-menu-proyectos": "Projects",
      "footer-menu-contacto": "Contact"
    }
  }
};

let currentLang = localStorage.getItem('language') || 'es';

// Set language and update text
function setLanguage(lang) {
  currentLang = lang;
  localStorage.setItem('language', lang);
  console.log('Language changed to:', lang); // Depuración
  
  // Update all elements with data-lang attributes
  document.querySelectorAll('[data-lang]').forEach(element => {
    const key = element.getAttribute('data-lang');
    const section = element.getAttribute('data-section');
    if (translations[lang] && translations[lang][section] && translations[lang][section][key]) {
      element.innerHTML = translations[lang][section][key];
    }
  });

  // Update placeholder attributes
  document.querySelectorAll('[data-lang-placeholder]').forEach(element => {
    const key = element.getAttribute('data-lang-placeholder');
    const section = element.getAttribute('data-section');
    if (translations[lang] && translations[lang][section] && translations[lang][section][key]) {
      element.placeholder = translations[lang][section][key];
    }
  });

  // Update language button text
  const langButton = document.getElementById('lang-toggle');
  if (langButton) {
    langButton.textContent = lang === 'es' ? 'EN' : 'ES';
  }
}

// Toggle language
function toggleLanguage() {
  const newLang = currentLang === 'es' ? 'en' : 'es';
  console.log('Toggling to language:', newLang); // Depuración
  setLanguage(newLang);
}

// Initialize
document.addEventListener('DOMContentLoaded', () => {
  console.log('Initializing language:', currentLang); // Depuración
  setLanguage(currentLang);
  const langButton = document.getElementById('lang-toggle');
  if (langButton) {
    langButton.addEventListener('click', toggleLanguage);
  }
});